### ISSUE TITLE
Getting Error: Requested column: 0, # of columns: 0

### ISSUE THREAD

**Issue by embpdaniel** [dgladkov/react-native-image-rotate#10]
Hi, I am attempting to rotate an image returned by [react-native-image-picker](https://github.com/react-community/react-native-image-picker), but I am having trouble getting it to work. The response data of the picker gives me something like this:

```
fileName: "image-95d7bc92-8982-4e5c-80c3-a467c089b910.jpg"
fileSize: 1903989
height:2340
isVertical: false
originalRotation: 90
path: "/storage/emulated/0/Pictures/image-95d7bc92-8982-4e5c-80c3-a467c089b910.jpg"
timestamp: "2018-03-07T16:23:31Z"
type: "image/jpeg"
uri: "content://com.myapp.provider/app_images/Pictures/image-95d7bc92-8982-4e5c-80c3-a467c089b910.jpg"
width: 4160
```

Based on the example I saw for rotating an image, it looks like the uri I should provide should be

`content://com.myapp.provider/app_images/Pictures/image-95d7bc92-8982-4e5c-80c3-a467c089b910.jpg`

I pass this uri along with the angle (90), and I get this error when doing so:
`Requested column: 0, # of columns: 0`

I figured maybe I was passing the wrong path, so I tried using the path value (`/storage/emulated/0/Pictures/image-95d7bc92-8982-4e5c-80c3-a467c089b910.jpg`) but passing that tells me this path is invalid since it has no protocol. So I think the correct uri is in fact the one I originally passed. Additionally, at the same time as I try to rotate, I display the image to the user, using the uri value, and this displays just fine. So I know the image does exist and it is valid.

Any idea why I would get this error? I am targeting Android, and my test device uses Android 6.0. 
Thank you in advance!

**Comment by filipef101** [comment]
add file:// to the path

**Comment by filipef101** [comment]
I'm fetching an image from cache just fine

**Comment by dgladkov** [comment]
@filipef101 is correct, local paths should have a `file://` scheme, while gallery returns `content://` scheme.

See this answer: https://stackoverflow.com/questions/6301215/converting-file-scheme-to-content-scheme
