### ISSUE TITLE
Unable to read rotated image uri "rct-image-store://0" in iOS

### ISSUE THREAD

**Issue by durgaganesh** [dgladkov/react-native-image-rotate#13]
Hi,

This library works very fine!! I am able to read the rotated image (rotate to 9o degree) just fine in Android emulator. But the rotated image uri is receiving as "rct-image-store://0" for iOS simulator. And I am unable to get image path from "rct-image-store://0"

I am using [rn-fetch-blob](https://github.com/joltup/rn-fetch-blob#readme)  to convert the image url into multipartData. The image url "rct-image-store://0" is not recognized at this point

Here is my code
```
_rotateImage() {
     ImageRotate.rotateImage(
       this.state.selectedImage,
       90,
       (uri) => {
         this.setState({
           selectedImage: uri, 
           width: this.state.height,
           height: this.state.width
         })
       },
       (error) => {
         console.error("rotateImage = " + error);
       }
     );
   }
```

**Comment by ggunti** [comment]
You should use ImageStore to get base64 of your image on iOS (see https://facebook.github.io/react-native/docs/imagestore ). Example of usage (in combination with react-native-fs library):

              ImageStore.getBase64ForTag(
                rotatedUri,
                (base64Image) => {
                  const imagePath = `${RNFS.DocumentDirectoryPath}/${new Date().getTime()}.jpg`;
                  RNFS.writeFile(imagePath, `${base64Image}`, 'base64')
                  .then((success) => {
                    // now your file path is imagePath (which is a real path)
                    ImageStore.removeImageForTag(rotatedUri); 
                  })
                  .catch((err) => console.log('RNFS writeFile error: ', err));
                },
                (err) => { }
              );

**Comment by dgladkov** [comment]
`rct-image-store://0` and asset ids on android are not going to work here. You need actual local path to the image file as @ggunti suggested. Feel free to open PR to if you think this should be mentioned in README

**Comment by nihp** [comment]
@ggunti Solution worked for me. Thanks
