### ISSUE TITLE
Unfortunately, <app_name> has stopped (android)

### ISSUE THREAD

**Issue by ggunti** [dgladkov/react-native-image-rotate#14]
Try exactly this:

    RNImageRotate.rotateImage(
      https://i.imgur.com/9qtVISH.jpg,
      90,
      (rotatedUri) => {
        console.log(rotatedUri);
      },
      (err) => {
        console.log(err);
      }
    );

It crashes the entire app at me ( mobile device: Samsung S5, "react": "16.5.0", "react-native": "^0.57.1", "react-native-image-rotate": "^2.1.0" )
![image](https://user-images.githubusercontent.com/26307699/47264499-09367100-d521-11e8-82b4-8cfd2e9c9f30.png)

Obviously it crashes because we are out of memory. But it shouldn't crash, it should call the error callback function with corresponding message.
As a workaround, I modified the `private Bitmap rotate(BitmapFactory.Options outOptions)` function like this:

        private Bitmap rotate(BitmapFactory.Options outOptions) throws IOException {
            InputStream inputStream = openBitmapInputStream();
            try {
                // This can use a lot of memory
                Bitmap bitmap = BitmapFactory.decodeStream(inputStream, null, outOptions);
                if (bitmap == null) {
                    throw new IOException("Cannot decode bitmap: " + mUri);
                }
                Matrix rotateMatrix = new Matrix();
                rotateMatrix.postRotate(mAngle);

                return Bitmap.createBitmap(bitmap, 0, 0, bitmap.getWidth(), bitmap.getHeight(), rotateMatrix, true);
            } catch (OutOfMemoryError outOfMemoryError) {
                // we are out of memory
                throw new RuntimeException("We are out of memory");
            } finally {
                if (inputStream != null) {
                    inputStream.close();
                }
            }
        }

Now, in case we are out of memory, the app do not crash anymore. Instead we get the "We are out of memory" error message in the `(err) => { console.log(err); }` callback function.
It could be merged into the library...

**Comment by dgladkov** [comment]
Closed by #15
